# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23f9a46fbdc244428a2e3061e86c234e24e6140ca2be1bb085e35f1744cf50539469e8893eeadcaee399beb9cf614d50b329f50bac21516d277bfd7da4bb304c

test:
  secret_key_base: 64a6a8ae6cca5345f9a25867ef8521dd8e501bd5bc52cd71c90d8fd2e4be93cce3a58d41ad64bc41a1056040673849fb852326666128ecde0e9f2e0551b8e424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
